[package]
name = "seed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
bcrypt = "0.14.0"
dotenv = "0.15.0"
sqlx = "0.6.2"
tokio = { version = "1.26.0", features = ["full"] }
